services:
  - type: web
    name: nepal-digital-bank-api
    env: docker
    plan: free
    repo: https://github.com/AronWahooo/nepal-digital-bank
    branch: main
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true

databases:
  - name: nepal-db
    plan: free
